name: fluotracify-tf-nightly
channels:
  - defaults
  - conda-forge
#   - file:///home/lex/Programme/drmed-git/src/
dependencies:
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
    - tf-nightly
    - mlflow
