name: fluotracify-tf
channels:
  - defaults
  - conda-forge
#   - file:///home/lex/Programme/drmed-git/src/
dependencies:
  - pip
  - pip:
    - numpy==1.19.5
    - tensorflow
    - mlflow
    - pandas
    - matplotlib
    - scikit-learn
